### ISSUE TITLE
不跨平台

### ISSUE THREAD

**Issue by F-Unction** [Duanyll/LuoguPaintboardPro#5]
```shell
> dotnet LuoguPaintboardPro.dll genpic pic.png
输入文件: pic.png
Unhandled exception. System.TypeInitializationException: The type initializer for 'Gdip' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'libgdiplus' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(liblibgdiplus, 1): image not found
   at System.Drawing.SafeNativeMethods.Gdip.GdiplusStartup(IntPtr& token, StartupInput& input, StartupOutput& output)
   at System.Drawing.SafeNativeMethods.Gdip..cctor()
   --- End of inner exception stack trace ---
   at System.Drawing.SafeNativeMethods.Gdip.GdipCreateBitmapFromFile(String filename, IntPtr& bitmap)
   at System.Drawing.Bitmap..ctor(String filename, Boolean useIcm)
   at LuoguPaintboardPro.ImageProcessor.ProcessImage(String input, String output) in /Users/f_unction/FromGit/LuoguPaintboardPro/LuoguPaintboardPro/ImageProcessor.cs:line 57
   at LuoguPaintboardPro.Program.<>c__DisplayClass0_1.<Main>b__3() in /Users/f_unction/FromGit/LuoguPaintboardPro/LuoguPaintboardPro/Program.cs:line 34
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at LuoguPaintboardPro.Program.Main(String[] args) in /Users/f_unction/FromGit/LuoguPaintboardPro/LuoguPaintboardPro/Program.cs:line 89
[1]    12974 abort      dotnet LuoguPaintboardPro.dll genpic pic.png
```

**Comment by Duanyll** [comment]
需要安装适合操作系统的libgdiplus
